-- Create experience table
create table experience (
  id bigint generated by default as identity primary key,
  role text not null,
  company text not null,
  period text not null,
  "desc" text not null,
  tech text [] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Enable RLS
alter table experience enable row level security;
-- Create policy to allow read access for everyone
create policy "Enable read access for all users" on experience for
select using (true);
-- Create policy to allow insert/update/delete for authenticated admin users only
create policy "Enable insert for authenticated users only" on experience for
insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on experience for
update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on experience for delete using (auth.role() = 'authenticated');
-- Verify existing tables (Run these if you haven't already)
-- Projects Table
create table if not exists projects (
  id bigint generated by default as identity primary key,
  title text not null,
  "desc" text,
  image text,
  tech text [],
  category text,
  link text,
  demo_url text,
  repo_url text,
  featured boolean default false,
  year text,
  client text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Certificates Table
create table if not exists certificates (
  id bigint generated by default as identity primary key,
  title text not null,
  issuer text,
  date text,
  image text,
  category text,
  credential_id text,
  link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);