-- ==============================================================================
-- 🚀 FULL SUPABASE SETUP SCRIPT UNTUK PORTFOLIO RIFAL (SEKALI COPAS) 🚀
-- ==============================================================================

-- 1️⃣ HAPUS TABEL LAMA (JIKA ADA) BIAR BERSIH
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS experience;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS certificates;
DROP TABLE IF EXISTS cv_uploads;

-- ==============================================================================
-- 2️⃣ BUAT SEMUA TABEL
-- ==============================================================================

-- A. TABEL PROJECTS
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Web Dev',
  tech JSONB DEFAULT '[]'::jsonb,
  image TEXT,
  year TEXT,
  featured BOOLEAN DEFAULT false,
  client TEXT,
  "desc" TEXT,
  demo_url TEXT,
  repo_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- B. TABEL EXPERIENCE
CREATE TABLE experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  company TEXT NOT NULL,
  period TEXT,
  year TEXT,
  "desc" TEXT,
  tech JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- C. TABEL SKILLS
CREATE TABLE skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  proficiency INTEGER DEFAULT 80,
  icon_name TEXT DEFAULT 'Code',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- D. TABEL CERTIFICATES
CREATE TABLE certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  org TEXT,
  year TEXT,
  category TEXT DEFAULT 'Engineering',
  image_url TEXT,
  credential_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- E. TABEL CV UPLOADS (UNTUK FILE PDF)
CREATE TABLE cv_uploads (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    file_url TEXT NOT NULL,
    file_name TEXT NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Hanya boleh ada satu CV aktif
CREATE UNIQUE INDEX idx_active_cv ON cv_uploads (is_active) WHERE is_active = true;

-- ==============================================================================
-- 3️⃣ ISI DATA AWAL (SEED DATA)
-- ==============================================================================

INSERT INTO projects (title, category, tech, image, year, featured, client, "desc", demo_url, repo_url) VALUES
('Climate Change Environmental Monitoring', 'Data Analytics', '["Python", "Tableau", "SQL", "Pandas"]', 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=600&auto=format&fit=crop', '2024', true, 'Personal Project', 'Dashboard interaktif untuk memantau data lingkungan dan perubahan iklim menggunakan analisis data Python dan visualisasi Tableau.', 'https://portofolio-nine-opal.vercel.app', 'https://github.com/rifalazhar'),
('Portfolio Website - Rifal Dev', 'Web Dev', '["React", "TypeScript", "Tailwind CSS", "Framer Motion"]', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop', '2025', true, 'Personal', 'Portfolio website modern dengan dark cyberpunk aesthetic, animasi framer motion, dan integrasi database real-time.', 'https://portofolio-nine-opal.vercel.app', 'https://github.com/rifalazhar');

INSERT INTO experience (role, company, period, year, "desc", tech) VALUES
('Digital Marketing & Data Analyst', 'Nevercode LTD', 'Jan 2024 - Present', '2024', 'Mengelola strategi konten digital, analisis data kampanye, dan optimasi SEO. Berhasil meningkatkan engagement rate hingga 150% dalam 6 bulan pertama.', '["Google Analytics", "SQL", "Python", "Tableau", "SEO"]'),
('Freelance Web Developer', 'Self-Employed', 'Jun 2023 - Present', '2023', 'Mengembangkan website dan aplikasi web untuk klien lokal menggunakan React, Next.js, dan WordPress. Menangani 5+ proyek selesai dengan kepuasan klien 100%.', '["React", "Next.js", "WordPress", "HTML/CSS", "JavaScript"]');

INSERT INTO skills (category, name, proficiency, icon_name) VALUES
('Frontend', 'React.js', 92, 'Atom'),
('Frontend', 'TypeScript', 88, 'Code'),
('Backend', 'SQL / MySQL', 90, 'Database'),
('Backend', 'Python', 92, 'Zap'),
('Tools', 'Git & GitHub', 88, 'Code');

INSERT INTO certificates (title, org, year, category) VALUES
('Machine Learning: K-Means Clustering', 'DQLab', 'March 2025', 'Engineering'),
('Mastering UI/UX with Figma', 'Gamelab Indonesia', 'August 2024', 'Engineering');

-- ==============================================================================
-- 4️⃣ PENGATURAN KEAMANAN & PENYIMPANAN
-- ==============================================================================

-- Buat storage bucket untuk nyimpen file
INSERT INTO storage.buckets (id, name, public) VALUES ('cv-files', 'cv-files', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('project-images', 'project-images', true) ON CONFLICT (id) DO NOTHING;

-- Buka akses public untuk storage dan tabel
ALTER TABLE cv_uploads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read cv" ON cv_uploads FOR SELECT USING (is_active = true);
CREATE POLICY "Allow auth all cv" ON cv_uploads FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow public read cv files" ON storage.objects FOR SELECT USING (bucket_id = 'cv-files' OR bucket_id = 'project-images');
CREATE POLICY "Allow auth all files" ON storage.objects FOR ALL USING (auth.role() = 'authenticated');

-- Hidupkan realtime untuk semua tabel
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table projects;
alter publication supabase_realtime add table skills;
alter publication supabase_realtime add table experience;
alter publication supabase_realtime add table certificates;
